### ISSUE TITLE
y no tests?

### ISSUE THREAD

**Issue by robinjoseph08** [itsachen/focaccia.life#3]
(」ﾟДﾟ)」⬅️  tfw there arent any tests

**Comment by peterdolan** [comment]
Problem: my application is comprised of an API component and a background processing component which uses WebJobs. All parts of the app use Serilog in order to send diagnostic messages to an elasticsearch cluster. I want each webjob's logs to appear in both the dashboard and in the elasticsearch cluster.

There are four possible solutions to this problem that I explored, none of which ended up working out completely for me:

Implement a custom Serilog Sink to handle pushing logs to webjobs, and implement a "passthru" TraceWriter which should be added to the JobHostConfiguration before initialization. Basically this was an attempt to "trick" WebJobs into recognizing that logging is happening and to send said logs to the dashboard. This is, IMO, the cleaner option overall as I would theoretically be able to just inject an ILogger instance everywhere and have logs magically appear where they need to be, but unfortunately when I implemented this, it seemed like all logs that my webjob sent (i.e. explicit ILogger.Information() calls) were being ignored, while runtime-generated logs such as exception messages worked fine and were logged to the dashboard. So this option didn't work at all for me.

Attempt to enable Console, Trace, File, etc. logging in Serilog in hopes of getting WebJobs to pick up one of them and send the logs to the dashboard. This didn't work despite some StackOverflow posts saying it would. :)

Implement a custom TraceWriter that has a serilog dependency. This actually worked and allowed logs to be stored in both the webjobs dashboard and the elasticsearch cluster. However, it's a messy solution because I had to call Serilog's internal message parser to generate a log that the dashboard would be able to display (it doesn't understand serilog's message templates). It's additionally messy because certain shared code needed both an ILogger dependency and an optional TraceWriter dependency for the case when the shared code is being invoked from the WebJobs runtime. I considered just using the TraceWriter that I wrote everywhere to avoid multiple logging dependencies, but that seemed a bit odd as I figured pieces of my application unrelated to WebJobs shouldn't have a WebJobs dependency

Use the built in TextWriter dependency injection stuff. This wasn't ideal for the same reason #3 wasn't ideal, and it was less flexible because TextWriter only exposes a WriteLine method and I want to be able to log errors, warnings, etc. differently.

So that said, is there a recommended approach for logging to external data sources and the dashboard at once? If webjobs just listened for Trace messages and wrote those to the dashboard, this would be a lot easier because I could simply turn on Trace logging and ElasticSearch logging in my Serilog configuration and be done with it, but it seems like this doesn't work / no longer works as of the latest stable WebJobs version.

Thanks!
 👍 3

**Comment by mgartner** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in eros mattis augue imperdiet iaculis in vel turpis. Etiam elit odio, congue in dui at, tristique tincidunt lorem. Vivamus vitae ultricies felis. Vestibulum nibh magna, vestibulum non odio et, malesuada auctor dui. Sed ut dui at mauris congue porta ac hendrerit tellus. Aenean vestibulum semper bibendum. In accumsan venenatis tellus nec lobortis. Suspendisse enim nibh, rutrum a tempus id, rutrum nec felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In efficitur mauris quis pretium sodales. In aliquam et odio vitae accumsan. Quisque quis ante augue. Fusce tincidunt mi id ligula mollis, non luctus magna mollis. Phasellus vel tincidunt velit. Suspendisse fermentum, mi at dictum ullamcorper, lectus ipsum volutpat diam, non dapibus eros dui nec ipsum. Curabitur rhoncus mauris felis, vel iaculis nibh volutpat non.

Phasellus vel varius ipsum. Vivamus porta, lectus at rutrum ullamcorper, augue enim varius eros, sit amet condimentum risus lacus vel odio. Praesent convallis pharetra odio fermentum tincidunt. Aliquam sagittis ornare tincidunt. Nulla facilisi. Cras vel odio eu libero rhoncus porttitor. Maecenas in tortor id lectus eleifend pharetra. Morbi semper diam id justo viverra molestie. Donec semper hendrerit ex ac condimentum. Duis in est eu purus faucibus tincidunt hendrerit quis urna. Phasellus vitae elit pellentesque, interdum dui sollicitudin, finibus eros. Vivamus molestie sit amet nibh fermentum condimentum. Aenean a sodales lorem. Vivamus sit amet tempor ex. Aliquam volutpat, magna quis consequat porta, lectus mi condimentum mauris, pretium varius odio velit sed risus. Integer quis lacus sit amet quam scelerisque facilisis.

Nullam vel fringilla magna. Phasellus hendrerit elementum commodo. Praesent sit amet nisl iaculis, auctor sapien sit amet, consequat est. Nunc quis quam ac elit mollis tristique consectetur in nunc. Nam vestibulum, mi in facilisis vulputate, enim tortor blandit tortor, sed ullamcorper neque libero eget orci. Duis ante nisi, consectetur eu maximus quis, volutpat sit amet justo. Donec nec gravida lectus. Suspendisse a purus venenatis, vestibulum ipsum porta, scelerisque massa. Quisque in volutpat risus. Ut porta eget quam vel suscipit. Aliquam at porttitor felis. Cras posuere nulla et faucibus convallis. Mauris eu mauris eget leo aliquam facilisis. Donec lobortis sem sed erat finibus, eget rhoncus leo imperdiet.

Praesent gravida vestibulum interdum. Sed magna lectus, suscipit at lorem in, posuere finibus libero. Fusce lobortis sit amet nisl a efficitur. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donec egestas a ipsum in aliquet. Vestibulum turpis leo, sodales ac tortor non, convallis tempus lacus. Nulla varius lectus ac volutpat viverra. Quisque volutpat sagittis erat, at ultrices nulla rhoncus nec. Integer vel congue ipsum, eget porttitor sapien. Sed malesuada lectus sapien, vel pellentesque ante pharetra eu.

Suspendisse libero massa, efficitur ut euismod sit amet, dictum nec velit. Morbi sagittis rutrum libero, eleifend fringilla sem imperdiet eget. Integer nunc ante, tincidunt eu justo non, euismod consectetur elit. Curabitur arcu purus, consequat non auctor vel, gravida sodales diam. Fusce scelerisque lacus sem, nec blandit massa gravida et. Vivamus mollis nunc vel velit viverra tristique quis faucibus lacus. Sed eget odio massa. Nulla id accumsan risus, in interdum metus. Phasellus condimentum eget libero ac mollis. Aenean facilisis ante in turpis vulputate, eu sollicitudin nisi malesuada. Pellentesque non metus a ligula malesuada imperdiet. Nullam vel aliquet felis.

**Comment by mpiercy827** [comment]
Spicy jalapeno bacon ipsum dolor amet kevin shoulder ribeye, venison ground round beef pig landjaeger meatball tri-tip pastrami doner beef ribs cupim. Sirloin burgdoggen pork chop flank frankfurter. Shank chuck spare ribs, picanha filet mignon beef ribs turkey. Meatloaf leberkas sausage, flank chicken filet mignon porchetta meatball ham hock short loin kielbasa rump fatback pastrami.

Chuck pastrami prosciutto tri-tip. Chuck filet mignon t-bone ribeye boudin. Sirloin bacon shankle meatloaf corned beef beef ribs tail flank, ribeye beef pork belly doner. Brisket jerky shoulder rump, drumstick pork belly pastrami biltong bacon cow chuck turducken corned beef ham hock. Brisket spare ribs bresaola rump porchetta pork loin burgdoggen cow pork ribeye tongue turkey salami. Drumstick ball tip bresaola chicken, fatback corned beef cupim shank short loin tri-tip leberkas.

Tenderloin andouille shoulder short ribs pancetta. Cow flank pork belly corned beef salami biltong beef prosciutto ham hock beef ribs rump tongue meatball bacon short ribs. Flank pig short loin, shoulder doner bacon short ribs sirloin. Leberkas flank pastrami meatball pork belly, short ribs short loin beef ribs biltong shoulder tongue doner tail. Strip steak venison turkey cupim t-bone ham turducken. Spare ribs burgdoggen shankle landjaeger, tongue pastrami ham hock fatback boudin shoulder.

Pork loin sirloin turducken, salami tail drumstick short ribs bresaola landjaeger prosciutto rump. Cow drumstick beef, landjaeger pork loin pig kevin tenderloin prosciutto porchetta swine. Porchetta burgdoggen doner picanha short loin brisket ham hock shank bresaola capicola short ribs tail ball tip t-bone. Shank flank porchetta beef ribs tenderloin prosciutto pancetta swine ground round tongue biltong doner leberkas ham hock. Pork belly jowl beef ribs, sausage pig bacon alcatra capicola landjaeger andouille. Brisket chuck alcatra pork belly cupim burgdoggen meatloaf prosciutto short ribs filet mignon.

Salami meatloaf tongue burgdoggen tenderloin brisket, shankle pastrami spare ribs picanha. Sausage drumstick ham short ribs, shank hamburger shankle kielbasa beef ribs bacon pork loin. Meatloaf burgdoggen t-bone pastrami, flank landjaeger leberkas porchetta brisket kevin jowl capicola tongue fatback. Short ribs drumstick corned beef shoulder pig swine ham turkey filet mignon. Hamburger turkey t-bone swine kevin. Ball tip rump chuck ground round hamburger kielbasa pastrami corned beef.

**Comment by dmlittle** [comment]
Chicken chicken, chicken, chicken chicken chicken chicken, chicken chicken chicken chicken chicken chicken [[4]](https://isotropic.org/papers/chicken.pdf). Chicken chicken chicken chicken, chicken chicken chicken: chicken chicken chicken chicken chicken chicken chicken chicken chicken. (chicken chicken chicken chicken chicken chicken, chicken chicken chicken chicken chicken chicken chicken!)

Chicken, chicken-chicken chicken chicken—chicken chicken, chicken chicken 95% chicken chicken-chicken chicken, chicken chicken chicken chicken—chicken chicken chicken chicken. Chicken, chicken chicken, chicken chicken chicken 1987. Chicken chicken chicken chicken chicken chicken-chicken-chicken chicken chicken chicken chicken chicken chicken, chicken chicken chicken chicken chicken chicken chicken. Chicken chicken, chicken chicken chicken chicken chicken chicken chicken (chicken chicken chicken chicken chicken, chicken chicken chicken chicken chicken chicken chicken chicken).

Chicken chicken chicken chicken chicken chicken, chicken chicken (chicken chicken chicken chicken chicken chicken) chicken chicken chickens chicken. Chicken chickens chicken chicken chicken chicken chicken “chicken” chicken chickens chicken. Chicken chicken, chicken-chicken chicken chickens, chicken chicken chicken chicken chicken chicken chicken.1 Chicken chicken’s “chicken” chicken chicken chicken chicken—chicken chicken chicken chicken chicken chicken, chicken chicken chicken chicken chicken chicken.

Chicken chicken chicken chicken chicken. Chicken-chicken chicken chicken chicken chicken chicken chicken, chicken chicken chicken chicken, chicken, chicken chicken chicken “chicken” chicken.  Chicken chicken chicken chicken chicken chicken chicken, chicken, chicken chicken. Chicken chicken, chicken chicken chicken chicken chicken, chicken chicken chicken chicken chicken chicken (chicken, chicken-chicken chicken chicken chicken-chicken chicken chicken-chicken chicken). Chicken, chicken chicken chicken chicken chicken chicken chicken chicken chicken chicken chicken.  Chicken chicken chicken chicken chicken chicken, chicken chicken chicken chicken chicken chicken chicken chicken chicken (chicken).  Chicken chicken chicken chicken chicken chicken chicken chicken chicken chicken chicken chicken chicken, chicken chicken chicken, chicken, chicken chicken chicken chicken.

Chicken chicken chicken, chicken chicken chicken, chicken chicken chickens chicken chicken chicken chicken. Chicken, chicken chicken chicken chicken chicken chicken chicken-chicken chicken, chicken chicken chickens Chicken 2. Chicken chicken chicken chicken chicken chicken chicken chicken chicken, chicken chicken chicken, chicken chickens chicken. Chicken chicken chicken chicken chicken chicken chicken chicken (chicken chicken Chicken 3), chicken chickens chicken chicken chicken (Chicken 4). Chicken chicken chicken chicken chicken, chicken chicken chickens chicken, chicken chicken chickens chickens chicken. Chicken chicken chicken chicken chicken chicken chicken.

**Comment by itsachen** [comment]
See #12
